repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.16
    hooks:
      # Update the uv lockfile
      - id: uv-lock
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.16
    hooks:
      - id: uv-export
