name: AZD Template Validation
on: 
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  template_validation:
    runs-on: ubuntu-latest
    name: azd template validation
    environment: azd-template-gallery
    steps:
      - uses: actions/checkout@v4

      - uses: microsoft/template-validation-action@Latest
        with:
          validateAzd: ${{ vars.AZD_VALIDATE }}
          useDevContainer: ${{ vars.AZD_USE_DEV_CONTAINER }}
        id: validation
        env:
          AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
          GITHUB_TOKEN: ${{ secrets.AZD_GITHUB_TOKEN }}

      - name: print result
        run: cat ${{ steps.validation.outputs.resultFile }}